import { NestFactory } from '@nestjs/core';
import { AppModule } from 'src/app.module';
import { CityService } from 'src/city/city.service';
import { CountryService } from 'src/country/country.service';

async function bootstrap() {
  const app = await NestFactory.createApplicationContext(AppModule);

  const cityService = app.get(CityService);
  const countryService = app.get(CountryService);

  // Fetch all countries
  const countries = await countryService.findAll();

  // Helper to find a country by name
  const findCountryId = (name: string) => {
    const country = countries.find((c) => c.name === name);
    if (!country) {
      throw new Error(
        `Country not found: ${name}. Make sure to run seed:countries first.`,
      );
    }
    return country.id;
  };

  const cities = [
    // ---------- BRAZIL ----------
    {
      name: 'Florianópolis',
      countryId: findCountryId('Brazil'),
      lat: -27.58,
      lng: -48.57,
      image:
        'https://res.cloudinary.com/dgoalhjj1/image/upload/v1758538278/cities/florianopolis_ybinghajak.jpg',
      weather: 'Humid subtropical; warm summers, mild winters',
      airQuality: 'Generally Good–Moderate; PM2.5 often in good range',
      bestTaxiApp: '99, Uber',
      visaEase:
        'Many nationalities visa-free; US/CA/AU require e-visa from Apr 10, 2025',
      internetSpeed: 'Median fixed broadband (Brazil): ~230–256 Mbps',
      safety:
        'Numbeo Safety Index (city): ~57 (moderate safer-by-BR standards)',
      fun: 'Beaches, surfing, hikes; lively high season',
      healthcareAccess: 'Numbeo Health Care Index (city): ~60 (Moderate/High)',
      temperature: 'Avg ~23°C annual',
      humidity: 'Avg ~75% annual',
      bestWayToCommute:
        'Car/scooter for beaches; buses intra-island; ride-hail widely used',
      currencyValue: '1 USD ≈ 5.3 BRL (Sep 2025)',
      medicalInsurance: 'Recommended; private clinics widely used by visitors',
      tipping: 'Restaurants often add 10% service (optional but customary)',
      tapWater: 'Not generally recommended; use filtered/bottled',
      population: 'Metro ~1.32M (2025 est.)',
      visitorsPerYear:
        'Seasonal; Santa Catarina ~+ high domestic influx (no solid city stat)',
      simAndEmergency:
        'SIM: Vivo, Claro, TIM; Emergencies: Police 190, Ambulance 192, Fire 193',
      costOfLiving: {
        mealCheapUSD: '~$7.74',
        mcMealUSD: '~$6.79',
        cappuccinoUSD: '~$2.64',
        beerPubUSD: '~$3.02',
        water2LUSD: '~$2.08',
        breadDailyUSD: '~$1.08',
        localTransportTicketUSD: '~$1.00–$1.20',
        monthlyPassUSD: '~$52.64',
        taxi8kmUSD: '~$10.38',
        gasoline1LUSD: '~$1.32',
        utilities85m2USD: '~$197.55',
        utilitiesStudioUSD: '~$130.75',
        internetUSD: '~$21.32',
        gymMonthlyUSD: '~$34.34',
        cinemaTicketUSD: '~$6.79',
        coworkingMonthlyUSD: '~$100–$180',
        rent1BRCityCenterUSD: '~$500–$800',
        rent1BROutsideCenterUSD: '~$350–$600',
        singlePersonMonthlyUSD: '≈ $950–$1,100 (excl. rent)',
        singlePersonMonthlyWithRentUSD: '≈ $1,450–$1,900',
      },
      internetRating: 8.5,
      costOfLivingRating: 5.5,
      safetyRating: 5.5,
      overallRating: 6.5,
    },
    {
      name: 'Rio de Janeiro',
      countryId: findCountryId('Brazil'),
      lat: -22.91,
      lng: -43.17,
      image:
        'https://res.cloudinary.com/dgoalhjj1/image/upload/v1758538431/cities/rio-de-janerio_vrrds2.jpg',
      weather: 'Tropical; hot, humid summers',
      airQuality: 'Variable; often Moderate, spikes in dry/hot periods',
      bestTaxiApp: 'Uber, 99',
      visaEase: 'US/CA/AU e-visa from Apr 10, 2025; many others visa-free',
      internetSpeed: 'Median fixed broadband (Brazil): ~230–256 Mbps',
      safety: 'Numbeo Safety Index (city): ~34 (low—exercise caution)',
      fun: 'Very high; beaches, nightlife, events',
      healthcareAccess: 'Numbeo Health Care Index (city): ~60 (Moderate/High)',
      temperature: 'Avg ~24–26°C annual',
      humidity: 'Avg ~74% annual',
      bestWayToCommute: 'Metro + BRT + ride-hail; avoid risky areas',
      currencyValue: '1 USD ≈ 5.3 BRL (Sep 2025)',
      medicalInsurance: 'Strongly recommended; private hospitals preferred',
      tipping: '10% service often added; not mandatory',
      tapWater: 'Best to drink bottled/filtered',
      population: 'Metro ~13.9M (2025 est.)',
      visitorsPerYear: '~2–3M international pre-COVID; rebounding',
      simAndEmergency: 'SIM: Vivo, Claro, TIM; Emergencies: 190/192/193',
      costOfLiving: {
        mealCheapUSD: '~$7.20–$9.20',
        mcMealUSD: '~$6.50–$7.50',
        cappuccinoUSD: '~$3.21',
        beerPubUSD: '~$2.08',
        localTransportTicketUSD: '~$1.10–$1.30',
        monthlyPassUSD: '~$49.06',
        taxi8kmUSD: '~$10.75',
        gasoline1LUSD: '~$1.13',
        internetUSD: '~$16.79',
        utilities85m2USD: '~$193.96',
        utilitiesStudioUSD: '~$199.25',
        gymMonthlyUSD: '~$30.57',
        cinemaTicketUSD: '~$11.51',
        coworkingMonthlyUSD: '~$100–$200',
        rent1BRCityCenterUSD: '~$600–$1,000',
        rent1BROutsideCenterUSD: '~$400–$750',
        singlePersonMonthlyUSD: '≈ $800–$1,050 (excl. rent)',
        singlePersonMonthlyWithRentUSD: '≈ $1,400–$2,000',
      },
      internetRating: 6.5,
      costOfLivingRating: 4.0,
      safetyRating: 3.5,
      overallRating: 4.5,
    },
    {
      name: 'São Paulo',
      countryId: findCountryId('Brazil'),
      lat: -23.56,
      lng: -46.64,
      image:
        'https://res.cloudinary.com/dgoalhjj1/image/upload/v1758538502/cities/sao_paulo_ygh8ua.jpg',
      weather: 'Tropical highland; warm, humid summers',
      airQuality: 'Often Moderate; can be Poor in dry season',
      bestTaxiApp: 'Uber, 99',
      visaEase: 'US/CA/AU e-visa from Apr 10, 2025; many others visa-free',
      internetSpeed: 'Median fixed broadband (Brazil): ~230–256 Mbps',
      safety: 'Numbeo Safety Index (city): ~38 (low–moderate)',
      fun: 'Excellent food/nightlife, culture, events',
      healthcareAccess: 'Numbeo Health Care Index (city): ~60 (Moderate/High)',
      temperature: 'Avg ~19–23°C annual',
      humidity: 'Avg ~78% annual',
      bestWayToCommute: 'Metro + CPTM trains + ride-hail',
      currencyValue: '1 USD ≈ 5.3 BRL (Sep 2025)',
      medicalInsurance: 'Recommended',
      tipping: '10% service common on bills',
      tapWater: 'Prefer filtered/bottled',
      population: 'Metro ~22.99M (2025 est.)',
      visitorsPerYear: 'High business travel; ~2M+ pre-COVID',
      simAndEmergency: 'SIM: Vivo, Claro, TIM; Emergencies: 190/192/193',
      costOfLiving: {
        mealCheapUSD: '~$9.25',
        mcMealUSD: '~$6.98',
        cappuccinoUSD: '~$3.40',
        beerPubUSD: '~$2.64',
        milk1LUSD: '~$1.10',
        eggs12USD: '~$2.64',
        tomatoes1kgUSD: '~$1.70',
        apples1kgUSD: '~$2.64',
        potatoes1kgUSD: '~$1.32',
        localTransportTicketUSD: '~$0.90–$1.20',
        monthlyPassUSD: '~$55.28',
        taxi8kmUSD: '~$8.49',
        gasoline1LUSD: '~$1.13',
        internetUSD: '~$16.60',
        utilities85m2USD: '~$124.06',
        utilitiesStudioUSD: '~$85.85',
        gymMonthlyUSD: '~$28.49',
        cinemaTicketUSD: '~$15.09',
        coworkingMonthlyUSD: '~$120–$220',
        rent1BRCityCenterUSD: '~$600–$1,100',
        rent1BROutsideCenterUSD: '~$400–$850',
        singlePersonMonthlyUSD: '≈ $1,000–$1,150 (excl. rent)',
        singlePersonMonthlyWithRentUSD: '≈ $1,600–$2,250',
      },
      internetRating: 7.0,
      costOfLivingRating: 4.5,
      safetyRating: 4.5,
      overallRating: 5.5,
    },

    // ---------- ITALY ----------
    {
      name: 'Rome',
      countryId: findCountryId('Italy'),
      lat: 41.9028,
      lng: 12.496,
      image:
        'https://res.cloudinary.com/dgoalhjj1/image/upload/v1758538634/cities/rome_krcym3.jpg',
      weather: 'Mediterranean; hot summers, mild winters',
      airQuality: 'Generally Good–Moderate',
      bestTaxiApp: 'Free Now, ItTaxi',
      visaEase:
        'Schengen: 90/180 rule; ETIAS pre-travel auth coming for visa-exempt',
      internetSpeed:
        'Median fixed broadband (Italy): ~120–200 Mbps (rising in 2025)',
      safety: 'Numbeo Safety Index (city): ~62 (moderate–good)',
      fun: 'Very high: history, food, nightlife',
      healthcareAccess: 'Numbeo Health Care Index (city): ~63 (High)',
      temperature: 'Avg ~21°C annual',
      humidity: 'Avg ~70% annual',
      bestWayToCommute: 'Metro, bus, tram; walk historic center',
      currencyValue: '1 USD ≈ €0.85 (Sep 2025)',
      medicalInsurance: 'Travel insurance recommended (EU emergency 112)',
      tipping: 'Not obligatory; small tips; “coperto” may apply',
      tapWater: 'Safe to drink (ACEA-managed)',
      population: 'Urban aggl. ~4.35M (2025 est.)',
      visitorsPerYear: 'Very high (~10M+ pre-COVID; rebounding)',
      simAndEmergency:
        'SIM: TIM, Vodafone, WindTre; Emergency: 112 (single EU)',
      costOfLiving: {
        mealCheapUSD: '~$18.82',
        mcMealUSD: '~$12.94',
        cappuccinoUSD: '~$2.42',
        beerPubUSD: '~$6.04',
        milk1LUSD: '~$1.97',
        eggs12USD: '~$5.34',
        tomatoes1kgUSD: '~$4.24',
        monthlyPassUSD: '~$41.18',
        taxi8kmUSD: '~$14.12',
        gasoline1LUSD: '~$2.08',
        gymMonthlyUSD: '~$69.18',
        cinemaTicketUSD: '~$22.35',
        coworkingMonthlyUSD: '~$200–$350',
        rent1BRCityCenterUSD: '~$1,100–$1,800',
        rent1BROutsideCenterUSD: '~$800–$1,200',
        singlePersonMonthlyUSD: '≈ $1,000–$1,100 (excl. rent)',
        singlePersonMonthlyWithRentUSD: '≈ $2,100–$2,900',
      },
      internetRating: 7.0,
      costOfLivingRating: 3.5,
      safetyRating: 6.0,
      overallRating: 5.5,
    },
    {
      name: 'Florence',
      countryId: findCountryId('Italy'),
      lat: 43.77,
      lng: 11.26,
      image:
        'https://res.cloudinary.com/dgoalhjj1/image/upload/v1758538792/cities/florence_q0xgct.jpg',
      weather: 'Mediterranean; warm summers, cool winters',
      airQuality: 'Generally Good–Moderate',
      bestTaxiApp: 'ItTaxi, Free Now',
      visaEase: 'Schengen: 90/180 rule',
      internetSpeed: 'Median fixed broadband (Italy): ~120–200 Mbps',
      safety: 'Numbeo Safety Index (city): ~69 (good)',
      fun: 'Arts, museums, food/wine',
      healthcareAccess: 'High (national system; private clinics available)',
      temperature: 'Avg ~16–17°C annual',
      humidity: 'Avg ~69% annual',
      bestWayToCommute: 'Walk/bike center; buses/trams',
      currencyValue: '1 USD ≈ €0.85 (Sep 2025)',
      medicalInsurance: 'Recommended',
      tipping: 'Not obligatory; small tips appreciated',
      tapWater: 'Safe to drink',
      population: 'Urban aggl. ~714k (2025 est.)',
      visitorsPerYear: 'High (tourism-heavy)',
      simAndEmergency: 'SIM: TIM, Vodafone, WindTre; Emergency: 112',
      costOfLiving: {
        mealCheapUSD: '~$17.65',
        mcMealUSD: '~$12.94',
        cappuccinoUSD: '~$2.72',
        beerPubUSD: '~$6.29',
        milk1LUSD: '~$1.49',
        eggs12USD: '~$4.35',
        tomatoes1kgUSD: '~$2.86',
        gasoline1LUSD: '~$2.08',
        monthlyPassUSD: '~$47.06',
        taxi8kmUSD: '~$23.53',
        gymMonthlyUSD: '~$65.88',
        cinemaTicketUSD: '~$23.53',
        coworkingMonthlyUSD: '~$180–$320',
        rent1BRCityCenterUSD: '~$1,000–$1,600',
        rent1BROutsideCenterUSD: '~$750–$1,200',
        singlePersonMonthlyUSD: '≈ $950–$1,050 (excl. rent)',
        singlePersonMonthlyWithRentUSD: '≈ $1,950–$2,600',
      },
      internetRating: 7.0,
      costOfLivingRating: 4.0,
      safetyRating: 6.5,
      overallRating: 6.0,
    },
    {
      name: 'Bologna',
      countryId: findCountryId('Italy'),
      lat: 44.494887,
      lng: 11.3426163,
      image:
        'https://res.cloudinary.com/dgoalhjj1/image/upload/v1758538790/cities/bologna_iglfp6.jpg',
      weather: 'Humid subtropical/oceanic mix; hot summers, cool winters',
      airQuality: 'Good–Moderate',
      bestTaxiApp: 'ItTaxi',
      visaEase: 'Schengen: 90/180 rule',
      internetSpeed: 'Median fixed broadband (Italy): ~120–200 Mbps',
      safety: 'Numbeo Safety Index (city): ~70 (good)',
      fun: 'Food capital; student nightlife',
      healthcareAccess: 'High (regional services strong)',
      temperature: 'Avg ~15°C annual',
      humidity: 'Avg ~70% annual',
      bestWayToCommute: 'Walk/bike center; buses',
      currencyValue: '1 USD ≈ €0.85 (Sep 2025)',
      medicalInsurance: 'Recommended',
      tipping: 'Not obligatory',
      tapWater: 'Safe to drink',
      population: 'Urban aggl. ~819k (2025 est.)',
      visitorsPerYear: 'Strong domestic/international mix',
      simAndEmergency: 'SIM: TIM, Vodafone, WindTre; Emergency: 112',
      costOfLiving: {
        mealCheapUSD: '~$15.29',
        mcMealUSD: '~$10.59',
        cappuccinoUSD: '~$1.76',
        beerPubUSD: '~$6.78',
        gymMonthlyUSD: '~$63.53',
        cinemaTicketUSD: '~$21.18',
        coworkingMonthlyUSD: '~$180–$300',
        rent1BRCityCenterUSD: '~$900–$1,400',
        rent1BROutsideCenterUSD: '~$700–$1,100',
        singlePersonMonthlyUSD: '≈ $900–$1,000 (excl. rent)',
        singlePersonMonthlyWithRentUSD: '≈ $1,600–$2,400',
      },
      internetRating: 7.0,
      costOfLivingRating: 4.5,
      safetyRating: 6.5,
      overallRating: 6.0,
    },

    // ---------- THAILAND ----------
    {
      name: 'Chiang Mai',
      countryId: findCountryId('Thailand'),
      lat: 18.79,
      lng: 98.99,
      image:
        'https://res.cloudinary.com/dgoalhjj1/image/upload/v1758539093/cities/chiang-mai_vnzmrs.jpg',
      weather: 'Tropical savanna; cool/dry season, hot season, rainy season',
      airQuality:
        'Seasonally Poor (burning season Feb–Apr); otherwise Moderate/Good',
      bestTaxiApp: 'Grab',
      visaEase:
        'Many visa-exempt 30–60 days; VoA & e-VOA for 31 nationalities; TDAC form required',
      internetSpeed: 'Median fixed broadband (Thailand): ~237 Mbps',
      safety: 'Numbeo Safety Index (city): ~74 (good)',
      fun: 'Cafés, coworking, markets, outdoor trips',
      healthcareAccess: 'Good private hospitals; high for expats/nomads',
      temperature: 'Avg ~25.1°C annual',
      humidity: 'Avg ~65% (dry) to 80% (rainy); annual ~70%',
      bestWayToCommute: 'Grab/tuk-tuk; scooters; red songthaews',
      currencyValue: '1 USD ≈ 32 THB (Sep 2025)',
      medicalInsurance: 'Recommended; private hospitals widely used',
      tipping: 'Not required; small tips appreciated',
      tapWater: 'Avoid drinking from tap; use bottled/filtered',
      population: 'Metro ~1.24M (2025 est.)',
      visitorsPerYear: 'High (peak in cool/dry months)',
      simAndEmergency:
        'SIM: AIS, True, DTAC; Emergencies: Police 191, Medical 1669, Fire 199',
      costOfLiving: {
        mealCheapUSD: '~$3.50–$4.50',
        mcMealUSD: '~$5.50–$6.50',
        cappuccinoUSD: '~$1.97',
        beerPubUSD: '~$2.44',
        monthlyPassUSD: '~$33.03',
        taxi8kmUSD: '~$19.25',
        gasoline1LUSD: '~$1.16',
        gymMonthlyUSD: '~$39.75',
        cinemaTicketUSD: '~$8.97',
        coworkingMonthlyUSD: '~$80–$150',
        rent1BRCityCenterUSD: '~$300–$600',
        rent1BROutsideCenterUSD: '~$200–$450',
        singlePersonMonthlyUSD: '≈ $700–$850 (excl. rent)',
        singlePersonMonthlyWithRentUSD: '≈ $1,000–$1,450',
      },
      internetRating: 6.5,
      costOfLivingRating: 7.5,
      safetyRating: 8.0,
      overallRating: 7.5,
    },
    {
      name: 'Phuket',
      countryId: findCountryId('Thailand'),
      lat: 7.89,
      lng: 98.39,
      image:
        'https://res.cloudinary.com/dgoalhjj1/image/upload/v1758539094/cities/phuket_ncu0iv.jpg',
      weather: 'Tropical monsoon; hot & very humid; dry Dec–Mar, wet May–Nov',
      airQuality: 'Often Good–Moderate; sea breeze helps; spikes during haze',
      bestTaxiApp: 'Grab (cars & bikes), local taxis',
      visaEase: 'Visa-exempt for many; VoA/e-VOA; TDAC required',
      internetSpeed: 'Median fixed broadband (Thailand): ~237 Mbps',
      safety: 'Numbeo Safety Index (province/city): ~66 (moderate–good)',
      fun: 'Beaches, diving, nightlife (Patong), island hopping',
      healthcareAccess: 'Good private hospitals/clinics',
      temperature: 'Typical 24–33°C; annual avg ~28°C',
      humidity: 'Avg ~77% annual',
      bestWayToCommute: 'Grab/taxi; scooters; limited buses',
      currencyValue: '1 USD ≈ 32 THB (Sep 2025)',
      medicalInsurance: 'Recommended',
      tipping: 'Not required; small tips appreciated',
      tapWater: 'Do not drink from tap; use bottled/filtered',
      population: 'Metro ~461k (2025 est.)',
      visitorsPerYear: 'Very high (top Thai beach destination)',
      simAndEmergency: 'SIM: AIS, True, DTAC; Emergencies: 191/1669/199',
      costOfLiving: {
        mealCheapUSD: '~$8.31',
        mcMealUSD: '~$7.81',
        cappuccinoUSD: '~$3.06',
        beerPubUSD: '~$3.34',
        milk1LUSD: '~$2.03',
        eggs12USD: '~$2.41',
        tomatoes1kgUSD: '~$2.09',
        gasoline1LUSD: '~$1.03',
        taxi8kmUSD: '~$19.38',
        gymMonthlyUSD: '~$69.06',
        cinemaTicketUSD: '~$13.59',
        coworkingMonthlyUSD: '~$120–$250',
        rent1BRCityCenterUSD: '~$600–$1,200',
        rent1BROutsideCenterUSD: '~$400–$800',
        singlePersonMonthlyUSD: '≈ $950–$1,100 (excl. rent)',
        singlePersonMonthlyWithRentUSD: '≈ $1,550–$2,300',
      },
      internetRating: 6.5,
      costOfLivingRating: 5.5,
      safetyRating: 6.0,
      overallRating: 6.0,
    },
    {
      name: 'Bangkok',
      countryId: findCountryId('Thailand'),
      lat: 13.73,
      lng: 100.56,
      image:
        'https://res.cloudinary.com/dgoalhjj1/image/upload/v1758539094/cities/bangkok_ltnwy7.jpg',
      weather: 'Tropical wet; hot year-round; rains May–Oct',
      airQuality: 'Moderate on average; can deteriorate seasonally',
      bestTaxiApp: 'Grab (cars & bikes), Bolt; BTS/MRT for core travel',
      visaEase: 'Visa-exempt (many) 30–60 days; VoA/e-VOA; TDAC required',
      internetSpeed: 'Median fixed broadband (Thailand): ~237 Mbps',
      safety: 'Numbeo Safety Index (city): ~57 (moderate)',
      fun: 'Very high: nightlife, food, malls, culture',
      healthcareAccess: 'Numbeo Health Care Index (city): ~81 (Very High)',
      temperature: 'Avg ~30°C annual',
      humidity: 'Avg ~73% annual',
      bestWayToCommute: 'BTS/MRT + Grab/Bolt; Airport Rail Link',
      currencyValue: '1 USD ≈ 32 THB (Sep 2025)',
      medicalInsurance: 'Recommended; excellent private hospitals',
      tipping: 'Not required; small tips common in service',
      tapWater:
        'MWA says treated, but most drink filtered/bottled due to pipes',
      population: 'Metro ~10–11M (city ~10M+; aggl. varies)',
      visitorsPerYear: 'Top global city (tens of millions, pre-COVID)',
      simAndEmergency:
        'SIM: AIS, True, DTAC; Emergencies: Police 191, Medical 1669, Fire 199',
      costOfLiving: {
        mealCheapUSD: '~$6.50',
        mcMealUSD: '~$6.03',
        cappuccinoUSD: '~$3.38',
        beerPubUSD: '~$4.00',
        monthlyPassUSD: '~$51.56',
        taxi8kmUSD: '~$6.25',
        gasoline1LUSD: '~$1.12',
        gymMonthlyUSD: '~$58.78',
        cinemaTicketUSD: '~$12.00',
        coworkingMonthlyUSD: '~$120–$250',
        rent1BRCityCenterUSD: '~$650–$1,300',
        rent1BROutsideCenterUSD: '~$450–$900',
        singlePersonMonthlyUSD: '≈ $950–$1,100 (excl. rent)',
        singlePersonMonthlyWithRentUSD: '≈ $1,600–$2,400',
      },
      internetRating: 7.5,
      costOfLivingRating: 5.5,
      safetyRating: 5.5,
      overallRating: 6.5,
    },
  ];

  await cityService.deleteAll();

  for (const c of cities) {
    try {
      await cityService.create(c as any);
      console.log(`Seeded ${c.name}`);
    } catch (err: any) {
      if (err.code === 11000) {
        console.log(`Already exists: ${c.name}`);
      } else {
        console.error(`Failed seeding ${c.name}`, err);
      }
    }
  }

  await app.close();
}

bootstrap();
